name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: logining to dockerhub 
    - uses: docker/login-active@v1
      with:
       username: $ {{secrets.DOCKER_HUB_USERNAME}}
       password: $ {{secrets.DOCKER_HUB_PASSWORD}}
       
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --fhassan008/apache:$(date +%s)


    
