name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: login to dockerhub 
      uses: docker/login-active@v1
      with:
       username: ${{secrets.DOCKER_HUB_USERNAME}}
       password: ${{secrets.DOCKER_HUB_PASSWORD}}
       
    
    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with: 
        push: true
        tags: fhassan008/apache:latest
      
      


    
